# Generated by Django 3.2.10 on 2021-12-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20211211_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
