# Generated by Django 3.2.10 on 2021-12-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20211211_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='LandType',
        ),
    ]
