# Generated by Django 3.2.10 on 2021-12-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_rename_type_landtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(),
        ),
    ]
