# Generated by Django 3.2.10 on 2021-12-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20211211_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
