# Generated by Django 3.2.10 on 2021-12-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='farm-5836815_1920.jpg', null=True, upload_to=''),
        ),
    ]
